export const allProjects = [
  {
    id: 1,
    title: "Harshit Portfolio",
    desc: "This is my Personal Portfolio Website that I build using Next.js, and Express.js APIs.",
    tech: `Next.js | React.js | CSS | Express.js | Vercel`,
    codeLink: "http://github.com/harshitkumar",
    liveLink: "https://harshitclub.com",
  },

  {
    id: 2,
    title: "Women Empowerment NGO",
    desc: "This is Women Empowerment NGO Website Name `Chal Naari`, I build this for my Company.",
    tech: `Next.js | React.js | CSS | Express.js | Vercel`,
    codeLink: "http://github.com/harshitclub/chalnaariweb",
    liveLink: "https://chalnaari.vercel.app/",
  },
  {
    id: 3,
    title: "Haiwebtech Marketing",
    desc: "Hai WebTech is a Digital Marketing website design that I build using core react.js.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/haiwebtechfiles",
    liveLink: "https://hai-web-tech.web.app/",
  },

  {
    id: 4,
    title: "Movie Search Website",
    desc: "Movie search website in which all the data comes from the TMDB movie website.",
    tech: `React.js | CSS | Redux | Github`,
    codeLink: "http://github.com/harshitclub/moviesflow",
    liveLink: "",
  },
  {
    id: 5,
    title: "Website Design React",
    desc: "Simple website design that I build using react.js and framer motion for animation.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/b2b-project",
    liveLink: "https://harshitclub.github.io/b2b-project/",
  },
  {
    id: 6,
    title: "React Simple Movies",
    desc: "Simple movie searching web application built with react.js and TMDB movie API.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/reactmoviesverse",
    liveLink: "https://reactmoviesverse.web.app/",
  },
  {
    id: 7,
    title: "React Shopping Cart",
    desc: "Shopping Cart project that I build with React.js and Context API with cart functions.",
    tech: `React.js | Context API | CSS | Github`,
    codeLink: "https://github.com/harshitclub/reactshoppingcart",
    liveLink: "https://rshopcart1.web.app/",
  },
  {
    id: 8,
    title: "React Simple Blog",
    desc: "Simple Blog Web page built with React.js in which we can select and see blog.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/react-blog",
    liveLink: "https://react-blog-5b9ba.web.app/",
  },
  {
    id: 9,
    title: "Firebase Auth React",
    desc: "Authentication Web App I build using React.js and Firebase for Authentication.",
    tech: `React.js | CSS | Firebase | Github`,
    codeLink: "https://github.com/harshitclub/react-auth-system",
    liveLink: "https://auth-system-40f0d.web.app/",
  },
  {
    id: 10,
    title: "React Js Weather App",
    desc: "Weather app in React.js in which you can enter your city name and see the weather.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/react-weather",
    liveLink: "https://harshitclub.github.io/react-weather/",
  },
  {
    id: 11,
    title: "React Contact Manager",
    desc: "Contact Manager built using react.js in which you can add and delete your contacts.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/react-contact-manager",
    liveLink: "https://harshitclub.github.io/react-contact-manager/",
  },
  {
    id: 12,
    title: "React Notes App",
    desc: "Notes Taking app built using React.js in which we can take and delete notes.",
    tech: `React.js | CSS | Github`,
    codeLink: "https://github.com/harshitclub/react-notes-app",
    liveLink: "https://harshitclub.github.io/react-notes-app/",
  },
];
